### ISSUE TITLE
Setting env var USER?

### ISSUE THREAD

**Issue by guettli** [vixie/cron#3]
I wasted some time to discover that then environment of a cronjob does not contain the variable USER.

Would you accept a patch to always set the variable, too?

I know that LOGNAME gets set, but somehow USER feels much more natural to me.

I use Version: 3.0pl1-136ubuntu1

**Comment by vixie** [comment]
different UNIX systems have different standards for the environment, and
cron tries to respect those. whatever your login shell sets as the variable
containing the login name, is what cron should set. on some systems this is
LOGNAME; on others it is USER; it is never both. cron will not try to reach
for some kind of universal portability that no normal shell on a given system
would be able to reliably expect.

**Comment by guettli** [comment]
Thank you for your reply.
