### ISSUE TITLE
Weekdays running outside of selected day range 

### ISSUE THREAD

**Issue by dvergur** [vixie/cron#6]
My expectations was that this would only run on Mondays within the date ranges between 1-7 and 15-21

`0 9 1-7,15-21 * 1`

Seams like it runs on Monday's outside this range to.

**Comment by vixie** [comment]
from crontab(5):

       Note: The day of a command's execution can be specified in the  fol-
       lowing  two  fields  —  'day  of month', and 'day of week'.  If both
       fields are restricted (i.e., do not contain the "*" character),  the
       command will be run when either field matches the current time.  For
       example, "30 4 1,15 * 5" would cause a command to be run at 4:30  am
       on  the 1st and 15th of each month, plus every Friday.

as in all things POSIX, please don't shoot the messenger. vixie cron implements an open specification.
